# Generated by Django 3.2.6 on 2021-08-31 14:39

import datetime
from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(blank=True, through='devblog.PostAuthor', to='devblog.Author', verbose_name='Authors of the article'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(verbose_name='Main body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, through='devblog.PostCategory', to='devblog.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 8, 31), verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, through='devblog.PostTag', to='devblog.Tag', verbose_name='Tags realted to the article'),
        ),
    ]
