# Generated by Django 3.2.6 on 2021-08-31 17:41

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0002_auto_20210831_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=froala_editor.fields.FroalaField(verbose_name='Main body'),
        ),
    ]
