# Generated by Django 3.2.6 on 2021-10-19 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0004_auto_20211011_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 10, 19), verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(help_text='This is the text usually shown in the menu or on hover', max_length=125, verbose_name='Short description'),
        ),
    ]
