# Generated by Django 3.2.6 on 2021-11-12 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0005_auto_20211019_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 11, 12), verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(help_text='This is the text usually shown in the menu or on hover', max_length=512, verbose_name='Short description'),
        ),
    ]
