# Generated by Django 3.2.6 on 2023-09-27 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0006_auto_20211112_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Publication date'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(default=datetime.date(2023, 9, 27), verbose_name='Publication date'),
        ),
    ]
