# Generated by Django 3.2.6 on 2021-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_users', '0002_auto_20211021_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='description',
            field=models.CharField(blank=True, max_length=264, verbose_name='Description'),
        ),
    ]
